Description of inv
Home > @quaternion > inv.m
inv
PURPOSE
INV Invert a unit-quaternion
SYNOPSIS
function qi = inv(q)
DESCRIPTION
INV Invert a unit-quaternion
    QI = inv(Q)
 Return the inverse of the unit-quaternion Q.
CROSS-REFERENCE INFORMATION
This function calls:
quaternion QUATERNION Constructor for quaternion objects
This function is called by:
mpower MPOWER Raise quaternion to integer power
mrdivide MRDIVIDE Compute quaternion quotient.
mtimes MTIMES Multiply two quaternion objects
SOURCE CODE
%INV Invert a unit-quaternion
%
%    QI = inv(Q)
%
% Return the inverse of the unit-quaternion Q.
%
% Copyright (C) 1999-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function qi = inv(q)
    qi = quaternion([q.s -q.v]);