Description of norm
Home > @quaternion > norm.m
norm
PURPOSE
NORM Compute the norm of a quaternion
SYNOPSIS
function n = norm(q)
DESCRIPTION
NORM Compute the norm of a quaternion
    QN = norm(Q)
 Return a unit-quaternion corresponding to the quaternion Q.
CROSS-REFERENCE INFORMATION
This function calls:
double DOUBLE Convert a quaternion object to a 4-element vector
norm NORM Compute the norm of a quaternion
This function is called by:
norm NORM Compute the norm of a quaternion
quaternion QUATERNION Constructor for quaternion objects
unit UNIT Unitize a quaternion
SOURCE CODE
%NORM Compute the norm of a quaternion
%
%    QN = norm(Q)
%
% Return a unit-quaternion corresponding to the quaternion Q.
%
% Copyright (C) 1993-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function n = norm(q)
    n = norm(double(q));