function dh = dhMatrix(theta, d, r, alpha)
    % PURPOSE - takes in DH parameters (meters and radians) and construct
    % the DH matrix from the data (theta, d, r, alpha)
    
    dh = [cos(theta) -sin(theta)*cos(alpha)  sin(theta)*sin(alpha) r*cos(theta); ...
          sin(theta)  cos(theta)*cos(alpha) -cos(theta)*sin(alpha) r*sin(theta); ...
          0           sin(alpha)             cos(alpha)            d;            ...
          0           0                      0                     1];
end