function rotMax = rotMatrix(theta, rotationAxis)
    % PURPOSE - takes in a theta (in radians) and a rotationalAxis ('x', 
    % 'y' or 'z') and returns a 3d rotational matrix.

    rotMax = zeros(4, 4);
    
    if strcmpi(rotationAxis, 'x')
        % rotates along x-axis, y towards z
        rotMax = ...
            [1          0            0; ...
             0          cos(theta)  -sin(theta); ...
             0          sin(theta)   cos(theta)];
         
    elseif strcmpi(rotationAxis, 'y')
        % rotates along y-axis, z towards x
        rotMax = ...
            [cos(theta)  0  sin(theta); ...
             0           1  0; ...
            -sin(theta)  0  cos(theta)];

    elseif strcmpi(rotationAxis, 'z')
        % rotates along z-axis, x towards y
        rotMax = ...
            [cos(theta)  -sin(theta)  0; ...
             sin(theta)   cos(theta)  0; ...
             0            0           1];
    end
end