Description of check
Home > mex > check.m
check
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
check1 CHECK script to compare M-file and MEX-file versions of RNE
stanford
stanfordm
This function is called by:
SOURCE CODE
fprintf('***************************************************************\n')
fprintf('************************ Puma 560 *****************************\n')
fprintf('***************************************************************\n')
clear
puma560
puma560akb
rdh = p560;
rmdh = p560m;
check1
fprintf('\n***************************************************************\n')
fprintf('********************** Stanford arm ***************************\n')
fprintf('***************************************************************\n')
clear
stanford
stanfordm
rdh = stan;
rdhm = stanm;
check1