Description of jacob0
Home > . > jacob0.m
jacob0
PURPOSE
JACOB0 Compute manipulator Jacobian in world coordinates
SYNOPSIS
function J0 = jacob0(robot, q)
DESCRIPTION
JACOB0 Compute manipulator Jacobian in world coordinates
    J0 = JACOB0(ROBOT, Q)
 Returns a Jacobian matrix for the robot ROBOT in pose Q.
 The manipulator Jacobian matrix maps differential changes in joint space
 to differential Cartesian motion (world coord frame) of the end-effector.
         dX = J dQ
 For an n-axis manipulator the Jacobian is a 6 x n matrix.
 See also: JACOBN, DIFF2TR, TR2DIFF.
CROSS-REFERENCE INFORMATION
This function calls:
fkine FKINE Forward robot kinematics for serial link manipulator
jacobn JACOBN Compute manipulator Jacobian in end-effector frame
t2r TR2ROT Return rotational submatrix of a homogeneous transformation
This function is called by:
cinertia CINERTIA Compute the Cartesian (operational space) manipulator inertia matrix
ikine IKINE Inverse manipulator kinematics
maniplty MANIPLTY Manipulability measure
SOURCE CODE
%JACOB0 Compute manipulator Jacobian in world coordinates
%
%    J0 = JACOB0(ROBOT, Q)
%
% Returns a Jacobian matrix for the robot ROBOT in pose Q.
%
% The manipulator Jacobian matrix maps differential changes in joint space
% to differential Cartesian motion (world coord frame) of the end-effector.
%         dX = J dQ
%
% For an n-axis manipulator the Jacobian is a 6 x n matrix.
%
% See also: JACOBN, DIFF2TR, TR2DIFF.
% Copyright (C) 1999-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function J0 = jacob0(robot, q)
    %
    %   dX_tn = Jn dq
    %
    Jn = jacobn(robot, q);    % Jacobian from joint to wrist space
    %
    %  convert to Jacobian in base coordinates
    %
    Tn = fkine(robot, q);    % end-effector transformation
    R = t2r(Tn);
    J0 = [R zeros(3,3); zeros(3,3) R] * Jn;