Description of numrows
Home > . > numrows.m
numrows
PURPOSE
NUMROWS(m)
SYNOPSIS
function r = numrows(m)
DESCRIPTION
 NUMROWS(m)
    Return the number of rows in the matrix m
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eul2r EUL2R Convert Euler angles to homogeneous transformation
eul2tr EUL2TR Convert Euler angles to homogeneous transformation
rne RNE Compute inverse dynamics via recursive Newton-Euler formulation
rpy2r RPY2R Roll/pitch/yaw to rotation matrix
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
SOURCE CODE
%
% NUMROWS(m)
%
%    Return the number of rows in the matrix m
%
function r = numrows(m)
    [r,x] = size(m);