Description of roty
Home > . > roty.m
roty
PURPOSE
ROTY Rotation about Y axis
SYNOPSIS
function r = roty(t)
DESCRIPTION
ROTY Rotation about Y axis
    R = ROTY(theta)
 Returns a 3x3 rotation matrix representing a rotation of theta
 about the Y axis.
 See also: ROTX, ROTZ, ROTVEC.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eul2r EUL2R Convert Euler angles to homogeneous transformation
eul2tr EUL2TR Convert Euler angles to homogeneous transformation
rpy2r RPY2R Roll/pitch/yaw to rotation matrix
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
troty TROTY Rotation about Y axis
SOURCE CODE
%ROTY Rotation about Y axis
%
%    R = ROTY(theta)
%
% Returns a 3x3 rotation matrix representing a rotation of theta
% about the Y axis.
%
% See also: ROTX, ROTZ, ROTVEC.
% Copyright (C) 1993-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function r = roty(t)
    ct = cos(t);
    st = sin(t);
    r =    [ct    0    st
        0    1    0
        -st    0    ct];