Description of ishomog
Home > . > ishomog.m
ishomog
PURPOSE
ISHOMOG Test if argument is a homogeneous transformation
SYNOPSIS
function h = ishomog(tr)
DESCRIPTION
ISHOMOG Test if argument is a homogeneous transformation
    H = ISHOMOG(TR)
  Returns true (1) if the argument tr is of dimension 4x4.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ikine IKINE Inverse manipulator kinematics
ikine560 IKINE560 Inverse kinematics for Puma 560
t2r TR2ROT Return rotational submatrix of a homogeneous transformation
transl TRANSL Create translational transform
SOURCE CODE
%ISHOMOG Test if argument is a homogeneous transformation
%
%    H = ISHOMOG(TR)
%
%  Returns true (1) if the argument tr is of dimension 4x4.
% Copyright (C) 2002-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function h = ishomog(tr)
    if ndims(tr) == 2,
        h =  all(size(tr) == [4 4]);
    else
        h = 0;
    end