Description of numcols
Home > . > numcols.m
numcols
PURPOSE
NUMCOLS(m)
SYNOPSIS
function c = numcols(m)
DESCRIPTION
 NUMCOLS(m)
    Return the number of columns in the matrix m
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eul2r EUL2R Convert Euler angles to homogeneous transformation
eul2tr EUL2TR Convert Euler angles to homogeneous transformation
fkine FKINE Forward robot kinematics for serial link manipulator
gravload GRAVLOAD Compute the gravity loading on manipulator joints
rne RNE Compute inverse dynamics via recursive Newton-Euler formulation
rpy2r RPY2R Roll/pitch/yaw to rotation matrix
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
SOURCE CODE
%
% NUMCOLS(m)
%
%    Return the number of columns in the matrix m
%
function c = numcols(m)
    [x,c] = size(m);