Description of unit
Home > . > unit.m
unit
PURPOSE
UNIT Unitize a vector
SYNOPSIS
function u = unit(v)
DESCRIPTION
UNIT Unitize a vector
    VN = UNIT(V)
 Returns a unit vector aligned with V.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
oa2r OA2R Convert O/A vectors to rotation matrix
oa2tr OA2TR Convert O/A vectors to homogeneous transformation
tr2angvec TR2ANGVEC Convert to angle/vector form
trnorm TRNORM Normalize a homogeneous transformation.
SOURCE CODE
%UNIT Unitize a vector
%
%    VN = UNIT(V)
%
% Returns a unit vector aligned with V.
% Copyright (C) 1990-2008, by Peter I. Corke
%
% This file is part of The Robotics Toolbox for Matlab (RTB).
%
% RTB is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% RTB is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with RTB.  If not, see <http://www.gnu.org/licenses/>.
function u = unit(v)
    u = v / norm(v,'fro');